export const QUOTES = [
  { text: '"Success is the product of daily habits—not once-in-a-lifetime transformations."', author: 'James Clear' },
  { text: '"We are what we repeatedly do. Excellence, then, is not an act, but a habit."', author: 'Aristotle' },
  { text: '"Motivation gets you started. Habit keeps you going."', author: 'Jim Ryun' },
  { text: '"Your net worth to the world is usually determined by what remains after your bad habits are subtracted from your good ones."', author: 'Benjamin Franklin' },
  { text: '"The secret of your future is hidden in your daily routine."', author: 'Mike Murdock' },
  { text: '"Small daily improvements are the key to staggering long-term results."', author: 'Robin Sharma' },
  { text: '"You do not rise to the level of your goals. You fall to the level of your systems."', author: 'James Clear' },
  { text: '"Compound interest is the eighth wonder of the world."', author: 'Albert Einstein' },
  { text: '"The chains of habit are too light to be felt until they are too heavy to be broken."', author: 'Warren Buffett' },
  { text: '"An investment in yourself pays the best interest."', author: 'Benjamin Franklin' },
  { text: '"The best time to plant a tree was 20 years ago. The second best time is now."', author: 'Chinese Proverb' },
  { text: '"Every action you take is a vote for the type of person you wish to become."', author: 'James Clear' },
  { text: '"Discipline is the bridge between goals and accomplishment."', author: 'Jim Rohn' },
  { text: '"The difference between who you are and who you want to be is what you do."', author: 'Unknown' },
  { text: '"A year from now you may wish you had started today."', author: 'Karen Lamb' },
  { text: '"Don\'t count the days. Make the days count."', author: 'Muhammad Ali' },
  { text: '"Win the morning, win the day."', author: 'Tim Ferriss' },
  { text: '"Hard choices, easy life. Easy choices, hard life."', author: 'Jerzy Gregorek' },
  { text: '"The only bad workout is the one that didn\'t happen."', author: 'Unknown' },
  { text: '"Progress, not perfection."', author: 'Unknown' },
  { text: '"What gets measured, gets managed."', author: 'Peter Drucker' },
  { text: '"The journey of a thousand miles begins with a single step."', author: 'Lao Tzu' },
  { text: '"First we make our habits, then our habits make us."', author: 'Charles C. Noble' },
  { text: '"You are the average of the five habits you repeat most."', author: 'Vicissometer' },
  { text: '"1% better every day. That\'s all it takes."', author: 'Vicissometer' },
]
